### ISSUE TITLE
Beacon Algorithm Excludes Trivial Case

### ISSUE THREAD

**Issue by zkhalapyan** [zkhalapyan/KimonoNet#16]
Although it's clear from the context, it would be correct to include what happens when a beacon arrives from a completely new peer. Here is an excerpt form the current version of the protocol that describes beacon exchange:

```
When PKT-BEACON arrives via UDP broadcast: 
• If HDR-SRC-ID is the same as the node's ID:
     o  Discard PKT-BEACON and exit.
• If HDR-SRC-LOC is newer than ROUTING-TABLE[HDR-SRC-ID], 
     o  Update ROUTING-TABLE[HDR-SRC-ID] = HDR-SRC-LOC
• For each NEIGHBOR-REPORT:
     o  If NEIGHBOR-LOC is newer than ROUTING-TABLE[NEIGHBOR-ID]
        Update ROUTING-TABLE[NEIGHBOR-ID] = NEIGHBOR-LOC
• Create PKT-BEACON-ACK for node and send via UDP broadcast.
• Reset TMR-BEACON.
```

**Comment by zkhalapyan** [comment]
Also, in what scenario is _HDR-SRC-ID is the same as the node's ID_ going to be true?

**Comment by ebollens** [comment]
I'll add if there is no value in ROUTING-TABLE-2.

I should also update the documentation to specify ROUTING-TABLE-2 specifically, since ROUTING-TABLE-1 is calculated from it and we shouldn't be modifying ROUTING-TABLE-1 directly.

And HDR-SRC-ID might be the same in the scenario where there's loopback. This scenario is covered in almost every broadcast/multicast/promiscuous protocol.
