### ISSUE TITLE
Packet Format and Types

### ISSUE THREAD

**Issue by zkhalapyan** [zkhalapyan/KimonoNet#2]
The idea is to have a superclass _Packet_ object that can encapsulate common packet handling and assembling functionality. With this scheme each packet will consist of a constant length header section and a variable length content section. Furthermore, header section with a total of 12 bytes will include the following fields:
1. magic flag (2)
2. version flag (1) 
3. type (1)
4. timestamp (8)

Packet type is a flag represented by a single byte and supports the following types:
1. BEACON (0x01)
2. HANDSHAKE (0x02)
3. DATA (0x03)

Given this parent _Packet_ class, various subclasses such as _BeaconPacket_, _DataPacket_, etc. will add more functionality to the generic packet class and add meaning to the contents field. 

Is there anything else to add to this packet structure? Hop count? or TTL?

**Comment by ebollens** [comment]
Here's how I'm seeing the breakdown based on the algorithm:

**General Header**
- **Version (1)** A reserved field that will always be 1 for the sake of this project.
- **Type (1)** A field that will be 0 on data, 2 on beacon, or 3 on beacon acknowledgement
- **Timestamp (4)** Accurate to the second, this can be Unix timestamp
- **Source ID (4)** The address of the source node
- **Source Location (8)** Two single-precision floats (4 bytes each) for longitude and latitude of position
- **Source Velocity (8)** Two single-precision floats (4 bytes each) for longitude and latitude of velocity vector

Following the general header, then you have the type-specific header.

**Type 0 (Data) Header**
- **Destination ID (4)** The address of the destination node - forwarded on unless this is the current node's ID
- **Destination Location (8)** Two single-precision floats (4 bytes each) for longitude and latitude where packet should be directed
- **Data Length (2)**
- **Header Checksum (2)** CRC-16 up to this field in the header (or equivalent to the whole header CRC-16 when this field is 0x0000)

**Types 2 & 3 Header**
- **Neighbor Count (1)** The number of neighbor descriptions expected in the data payload. This defines the length of the packet as a factor of the combined header length and then a multiple of the number contained in this field.
- **Reserved (1)** Just an empty bit for 4 byte word alignment purposes
- **Pull Packet Checksum (2)** CRC-16 of the entire contents of the packet (including the neighbor descriptions)

For Types 2 & 3, following the header, then there are a set of neighbor descriptions (the number of which is defined by Neighbor Count). These descriptions describe all _direct neighbors_ that the node sending the packet knows about. These are not further forwarded on. A node only includes in its own beacons and beacon acknowledgements the sum of nodes that are its direct neighbors.

__Type 2 & 3 Neighbor Descriptions __
- **Neighbor ID (4)** The address of the source node
- **Neighbor Location (8)** Two single-precision floats (4 bytes each) for longitude and latitude of position
- **Neighbor Velocity (8)** Two single-precision floats (4 bytes each) for longitude and latitude of velocity vector

A few asides...
- I made data as Type 0 because that fits the convention of many protocols. I also looked at the encoding on the type as having the following where the least significant bit denotes acknowledgement (so odd-numbered types are acknowledgement) and then the second least significant bit is the beacon concept. The reason is that, if for some reason, we need to add a data acknowledgement for our reliable QoS, we will add it as type 1, as it would be an acknowledgement to data.
- Although Type 0 and Types 2 & 3 use source location and velocity differently, they both need it. Therefore, it makes sense to put it in the header. In the case of Type 0, this dictates how selection of the next hop is made, while in the case of Types 2 & 3, this information is the beacon data for the sender node.
- The checksum for Type 0 is _just for the header_ up to the checksum field, while for Types 2 & 3, it is for the entire contents including the data payload of neighbors. This is because we don't want to consider neighbors if they're inaccurate.
- Types 2 and 3 have exactly the same composition. The difference is in terms of the algorithm, namely whether an acknowledgement is sent or not. See the requirements document (III.2) for more explanation on this if interested.

This all make sense?

**Comment by ebollens** [comment]
I realized there are a couple discrepancies in what I described above... Please see the following instead:

**General Packet Format**

All KimonoNet packets contain two components:
- Common Header
- Type-specific Payload

The common header type field (HDR-TYPE) defines the type-specific payload.

Each type-specific payload includes a fixed-width header and a variable length data segment. This type-specific payload must define a checksum that covers the common header fields, but it is defined in the type-specific payload component because it may optionally also cover additional fields.
The full length of the header (common and type-specific combined) must be 4-byte word aligned. If it is not, then any extra bytes to achieve this alignment should be composed of 0x00.

The common header includes the following fields:
- HDR-VERSION (1)
- HDR-TYPE (1)
- HDR-SRC-ID (4)
- HDR-SRC-LOC (8)
- HDR-SRC-VEL (8)
- HDR-TIMESTAMP (4)

**Type 0 Payload Format**

Following the common header, the Type 0 payload defines several additional header fields.

These fields have several purposes:
- Define the destination for packet routing via HDR-DST-ID and HDR-DST-LOC.
- Define whether the forwarding mode is FWD-GREEDY or FWD-DETOUR.
- Define the size of the variable-length data in octets (maximum data length is 2048 bytes).
- Provide a CRC-16 checksum of common and Type 0 header fields with HDR-HDR-CHK set to 0.

The Type 0 header includes the following fields:
- HDR-DST-ID (4)
- HDR-DST-LOC (8)
- HDR-FWD-DST-ID (4)
- HDR-FWD-MODE (1)
- HDR-DATA-LEN (1)
- HDR-HDR-CHK (2)

**Type 2 & 3 Payload Format**

Following the common header, the Type 2 & 3 payload defines two additional header fields.

If HDR-NEIGHBOR-COUNT is greater than zero, then it has a non-zero data field with length as the multiple of HDR-NEIGHBOR-COUNT and the neighbor report packet length (24 bytes). To keep packet size below 1500 bytes, HDR-NEIGHBOR-COUNT has a maximum value of sixty.

The Type 2 &3 header includes the following fields: 
- HDR-NEIGHBOR-COUNT (1)
- HDR-PKT-CHK (2)

Following the header, Type 2 & 3 packets include HDR-NEIGHBOR-COUNT neighbor reports.

**Type 2 & 3 Neighbor Report Format**

Each neighbor report is 24 bytes with the following fields:
- NEIGHBOR-ID (4)
- NEIGHBOR-LOC (8)
- NEIGHBOR-VEL (8)
- NEIGHBOR-TIMESTAMP (4)

**Comment by zkhalapyan** [comment]
This is all very good!
1. For GPS related values such as longitude & latitude, I used Java's primitive type double which is a double precision, 64-bit value as opposed to using single-precision floats. This decision was based on the return value of Android's [Location](http://developer.android.com/reference/android/location/Location.html) class which returns double values for lon & lat. Nevertheless, speed and accuracy will be denoted using floats.
2. Given that we are opening ports that listen to broadcast packets, generic header should include some 'magic' byte sequence in order to minimize packet parsing errors (or even worse - valid packets with invalid data). 
3. You skipped type-1, but it seems like you meant to have three packets type type-0, 1, and 2 instead of type-0, 2, 3. For naming convention, we should rename type-0 to Data Packet, type-1 to Beacon Packet, and type-2 to Handshake Packet. It is so much easier to understand the purpose of the packet type from an actual name than from a number. 
4. For addressing packets, I am using [IEEE MAC-48](http://en.wikipedia.org/wiki/MAC_address) standard which denotes an address using 6 bytes, instead of 8 bytes.

I want to look at these packets as objects that use inheritance to minimize duplicate code. So Packet will the be superclass with two children DataPacket and BeaconPacket. HandshakePacket will inherit from either BeaconPacket or Packet, depending on the functionality that they will share.

**Comment by zkhalapyan** [comment]
There is no need to include velocity and location inside the data packets as these values should be available to the routing algorithm via the beacon-handshake exchange. As such, the agent representing a peer will also have a hash table of neighboring peers with specified velocity and location.

**Comment by ebollens** [comment]
The protocol currently defines the following...

Common header:

```
HDR-MAGIC (2)
HDR-VERSION (1)
HDR-TYPE (1)
HDR-SRC-ID (8)
HDR-SRC-LOC (24)
HDR-SRC-VEC (12)
```

Location data  format:

```
LATITUDE (8)
LONGITUDE (8)
ACCURACY (4)
TIME (4)
```

Velocity data format:

```
SPEED (4)
BEARING (8)
```

Type 0 header:

```
HDR-DST-ID (8)
HDR-DST-LOC (24)
HDR-FWD-DST-ID (8)
HDR-FWD-MODE (1)
HDR-QOS (1)
HDR-DATA-LEN (2)
HDR-HDR-CHK (4)
```

Type 0 extended header (when HDR-FWD-MODE indicates that this is in perimeter mode - no checksum on these bits):

```
XHDR-ENTERED-LOC (24)
XHDR-FACE-ENTERED-LOC (24)
XHDR-FACE-FIRST-EDGE-SRC (24)
XHDR-FACE-FIRST-EDGE-DST (24)
```

Type 2 and 3 header format:

```
HDR-NEIGHBOR-COUNT (1)
HDR-PADDING (3)
HDR-PKT-CHK (4)
```

Neighborhood report format:

```
NEIGHBOR-ID (8)
NEIGHBOR-LOC (24)
NEIGHBOR-VEC (12)
```

Please let me know if any are still off.

**Comment by zkhalapyan** [comment]
One more correction: The inverse formula produces floats for both speed and bearing.

**Comment by ebollens** [comment]
What's the size of FLOAT in Java?

**Comment by zkhalapyan** [comment]
Floats are 4 bytes.

**Comment by ebollens** [comment]
I am thus updating the protocol's definition of vector data as:

```
SPEED (4)
BEARING (4)
```
