### ISSUE TITLE
PeerAddress.PeerAddress(Parcel parcel)

### ISSUE THREAD

**Issue by ghost** [zkhalapyan/KimonoNet#21]
Hi Zorayr,

(1) I noticed that before using <code>PeerAddress.PeerAddress(Parcel parcel)</code>, the parcel must be rewound by the caller.

(2) Also, after using the parcel, the parcel must be rewound again if it is to be used a second time by the caller.

Are these things intentional?

James

**Comment by ghost** [comment]
There is a more serious manifestation of this issue in <code>GeoLocation</code>. If you create a new instance of <code>GeoLocation</code> using the <code>GeoLocation.GeoLocation(byte[] buffer)</code> constructor, a new parcel is automatically created from the byte array. However, that parcel is not rewound. As a result, the subsequent call to <code>GeoLocation.setLocation(Parcel parcel)</code> to get values from the parcel will cause the program to crash.

So the question is, who is responsible for rewinding the parcel?

**Comment by zkhalapyan** [comment]
Every time a parcel is created from a byte array, which is equivalent of creating an empty parcel and adding a byte array, the parcel should be rewinded if it's going to be parsed into its smaller constituents. For example, when parsing a packet, a parcel is created from a byte array and then rewinded in order to extract the common header fields and also let beacon packet to extract its own fields. 

To see more details about how the parcel is working underneath, take a look at Java's [ByteBuffer](http://docs.oracle.com/javase/1.5.0/docs/api/java/nio/ByteBuffer.html). A parcel is a loose form of a stack where you can push and pop, but you can also mess with the "pointer position". What rewind does is set this pointer to 0, without affecting the byte buffer.

**Comment by ghost** [comment]
So I guess it is the responsibility of the user of a parcel to rewind whenever it needs to parse it. Which means I believe you need to add <code>parcel.rewind();</code> at the very top of the following code from <code>GeoLocation.java</code>.

``` java
    public void setLocation(Parcel parcel){
        this.longitude = parcel.getDouble();
        this.latitude  = parcel.getDouble();
        this.accuracy  = parcel.getFloat();
        this.timestamp = parcel.getInt();   
    }
```

**Comment by zkhalapyan** [comment]
The caller of `setLocation(Parcel parcel)` may or may not rewind the parcel before calling the method. The reason here is that within the parsing chain Packet (Type, Peer, Address, Location, etc) -> BeaconPacket (CRC, Peers, Peer Count, etc.), there will be only a single Parcel which is much more efficient than creating multiple parcels backed by multiple byte buffers.

I will try to amend the documentation to better reflect this behavior.

**Comment by ghost** [comment]
I see what you mean. So I guess <code>GeoLocation(byte[] buffer)</code> needs to be modified to rewind the parcel right after creating it, prior to passing it on to <code>GeoLocation(Parcel parcel)</code>, which then passes on the parcel to setLocation(Parcel parcel)</code>. Because right now, doing something like:

``` java
byte[] byteArray = {...}
GeoLocation location = new GeoLocation(byteArray);
```

would cause the program to crash.

**Comment by zkhalapyan** [comment]
Yes that is correct. For that matter, any constructor that takes a byte array should rewind the parcel, while constructors that take in a parcel should not.

**Comment by ghost** [comment]
Alright then. I will put a line note in your code regarding this issue.

**Comment by zkhalapyan** [comment]
A better approach: we eliminate all byte array constructors.
