### ISSUE TITLE
Re-Forming Data Packet When Entering Perimeter Mode

### ISSUE THREAD

**Issue by wnorris** [zkhalapyan/KimonoNet#26]
Should we incude a blank extended header all along or should we reformat the data packet to add a extended header when we enter into perimeter mode. Since adding this extra header segment will make the packet a different length we will have to create a whole new packet when entering perimeter mode.

Basically what is more important time or packet size?

**Comment by zkhalapyan** [comment]
As we discussed yesterday, I believe it would be better to sacrifice space her for increasing time-efficiency. Can you specify the number of extra bytes that will be included in the header? What is the total size of the header?

**Comment by wnorris** [comment]
According to the protocol it is an extra 96 bytes. The normal data header is 48 bytes.

**Comment by ebollens** [comment]
The protocol will not stipulate time or space efficiency - you can decide this in implementation.

**Comment by zkhalapyan** [comment]
The simplest approach would be to have two methods for parceling the data packet: one suitable for the greedy algorithm and the other one for the parameter routing. Within your _toParcel()_, decide which one is appropriate to call and return the parcel returned by that method.

Since data packet is going to be parsed and reassembled during transport, adding that extra 96 bytes is going to be just another headache for you.

**Comment by wnorris** [comment]
Got it.
