### ISSUE TITLE
Peer GeoLocation seems to not work

### ISSUE THREAD

**Issue by wnorris** [zkhalapyan/KimonoNet#48]
Finally realized while testing my code that it was dropping packets because all nodes were the same distance away. Checked into this and it seems that all Peers I create are at location 0, 0 no matter what.

```
    System.out.println("Starting Simulation");

    PeerAddress addressA = new PeerAddress("12:00:00:00:00:00");
    GeoLocation locationA = new GeoLocation(2000.0, 2000.0, 1.0f);

    PeerAddress addressB = new PeerAddress("12:00:00:00:00:01");
    GeoLocation locationB = new GeoLocation(0.0, 0.0, 1.0f);

    final Peer peerA = new Peer(addressA, locationA, new GeoVelocity(0f, 0f));
    final PeerAgent agentA = new PeerAgent(peerA);
    agentA.startServices();
    System.out.println("PeerA Location:\n"+agentA.getPeer().getLocation());

    final Peer peerB = new Peer(addressB, locationB, new GeoVelocity(0f, 0f));
    final PeerAgent agentB = new PeerAgent(peerB);
    agentB.startServices();
    System.out.println("PeerB Location:\n"+agentB.getPeer().getLocation());
```

Output:

Starting Simulation
PeerA Location:
Longitude: 0.0  Latitude: 0.0   Accuracy: 0.0   Timestamp: Mon Jan 05 16:49:37 PST 1970
PeerB Location:
Longitude: 0.0  Latitude: 0.0   Accuracy: 0.0   Timestamp: Mon Jan 05 16:49:37 PST 1970

**Comment by ghost** [comment]
Hi Wade,

Although this issue is assigned to Zorayr, I thought it might help that I chime in as well. Since no `GeoDevice` was specified for `PeerAgent`, the `DefaultGeoDevice` will be used. When you start the services, the `GeoService` continuously sets the location of the `Peer` according to whatever is returned by `GeoDevice.getLocation()`. But `DefaultGeoDevice.getLocation()` always returns `(Longitude, Latitude, Accuracy) = (0, 0, 0)`. I think that explains why you are experiencing this issue. It boils down to what `GeoDevice` you are using. I think we are going to be using `RandomWaypointGeoDevice` for the simulation.

Of course, Zorayr, feel free to correct if anything I said was wrong.

**Comment by zkhalapyan** [comment]
Hi Wade,

@james-h  is correct. The default GPS device emulator basically set the peer at the North poll with 0 velocity. 

I understand that this is a hassle for debugging, and hence, I changed the behavior of the default GPS emulator to maintain the peer at the initially specified location. The past two commits (7900d2b) and (a957136) modified `DefaultGeoDevice` and `PeerAgent` respectively, so make sure to update your copy.

**Comment by wnorris** [comment]
Got it , thanks!
