### ISSUE TITLE
Buffer Underflow Exception within DataPackets

### ISSUE THREAD

**Issue by zkhalapyan** [zkhalapyan/KimonoNet#51]
Running KiNCoL, I am getting several Buffer Underflow Exception with DataPackets parsing.

**Comment by zkhalapyan** [comment]
@wnorris, 

Pull the latest version, build it, go to the bin folder with the terminal, and type in the following command:

`java KimonoNet mode-cl 10 1000 1000 1 100 10`

This creates 10 randomly positioned peers within 1000m by 1000m region, with a hostility factor of 1 (you can ignore this value), speed of 100m/s, and sends 10 packets from a random source to another random source. 

During the simulation, you will see several BufferUnderflowExceptions with DataPackets.

@james-h, if you are also testing this, see if you can spot the bug.

**Comment by ghost** [comment]
`BufferUnderflowException`s with `DataPacket`s seem to be caused when `payloadLength` is too large. `payloadLength` should always be 2, but _sometimes_ it becomes some random number. My guess is that `payloadLength` _sometimes_ gets parsed incorrectly. Note I emphasize the word _sometimes_, so this might be a race condition caused by how the different threads interact.

**Comment by zkhalapyan** [comment]
@wnorris ,

`packetQueue` either needs to be blocking, or access to it should be synchronized. 

Edit: I changed the queue to `PriorityBlockingQueue` and it seemed to eliminate the problem.

**Comment by wnorris** [comment]
Hey man, how can I debug this? I can't really walk through what's going on with this command line interface.
