### ISSUE TITLE
Max Number of Neighbors to Include in a Beacon/BeaconAck Packet.

### ISSUE THREAD

**Issue by zkhalapyan** [zkhalapyan/KimonoNet#6]
There are two options to determine the number of neighbors to include in type-2/3 packets:
1. Max out the packet space. In other words, somehow calculate what is the maximum number that can fit inside a packet.
2. Have a constant number of neighbors that should be included in the packet.

With option (1) efficiency and complexity is an issue, while (2) might not be the best solution.

**Comment by ebollens** [comment]
To quote form the specification:

```
HDR-NEIGHBOR-COUNT has a maximum value of 34
```

The reason I did this is that it keeps the packet within 1500 bytes. However, can you make this configurable in the client? I think this is the sort of thing that we probably want to experiment with. If we don't get much better routing with a larger number, we might want to reduce it, or if it's a huge boon to routing efficiency, then we might want to expand it. However, this probably won't even rear it's head until we're testing hundreds upon hundreds of drones (since we're talking a sparse graph here, and to have 34 neighbors even if a bit less sparse than one would think).

**Comment by zkhalapyan** [comment]
Currently, I will try to include as many neighbors as possible, but I will introduce an environment variable to control the maximum number allowed. Also, could you please include the reasoning behind the "number 34" in the protocol documentation. When I read it over again, it just seems that the number pops out of no where with no reasonable explanation.

**Comment by ebollens** [comment]
I will add an explanation for 34 in the documentation, but that's because it's the most you can have while remaining under the 1500 byte MTU for Ethernet. Might actually be 33 now that I think about it, because of the header size for IP+UDP. However, since this doesn't have to be on top of IP+UDP, 34 is accurate, although your implementation may want to max out at 33. Please at least have an environment variable (or something that can be globally set) that defines the maximum number of neighbors in the report (or an MTU size is just fine if you want to compute as such internally).
